//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarConnectionSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int sequentialnumber { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string year { get; set; }
        public string msrp { get; set; }
        public string frontwheelsize { get; set; }
        public string horsepower { get; set; }
        public string displacement { get; set; }
        public string enginetype { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string length { get; set; }
        public string gasmileage { get; set; }
        public string drivetrain { get; set; }
        public string passengercapacity { get; set; }
        public string passengerdoors { get; set; }
        public string bodystyle { get; set; }
    }
}
